version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: ui_dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/Ecommerce

   
    networks:
      - my_network

  products:
    build: 
      context: .
      dockerfile: app_dockerfile
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/Ecommerce
    networks:
      - my_network
  shopping_cart:
    build: 
      context: .
      dockerfile: shoppingcart_dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/Ecommerce
    networks:
      - my_network
    

volumes:
  mongodb:

networks:

  my_network: